import React from 'react';

var Image_list = [];

Image_list = [
    '/glass.jpg', 
    '/picture1.jpg',
    '/picture2.jpg',
    '/picture3.jpg',
    '/IMG_5300.JPG',
    '/IMG_5301.JPG',
    '/glass.jpg', 
    '/picture1.jpg',
    '/picture2.jpg',
    '/picture3.jpg',
    '/IMG_5300.JPG',
    '/IMG_5301.JPG',
    '/glass.jpg', 
    '/picture1.jpg',
    '/picture2.jpg',
    '/picture3.jpg',
    '/IMG_5300.JPG',
    '/IMG_5301.JPG',
    '/glass.jpg', 
    '/picture1.jpg',
    '/picture2.jpg',
    '/picture3.jpg',
    '/IMG_5300.JPG',
    '/IMG_5301.JPG',
    '/glass.jpg', 
    '/picture1.jpg',
    '/picture2.jpg',
    '/picture3.jpg',
    '/IMG_5300.JPG',
    '/IMG_5301.JPG',
    '/glass.jpg', 
    '/picture1.jpg',
    '/picture2.jpg',
    '/picture3.jpg',
    '/IMG_5300.JPG',
    '/IMG_5301.JPG',
    '/glass.jpg', 
    '/picture1.jpg',
    '/picture2.jpg',
    '/picture3.jpg',
    '/IMG_5300.JPG',
    '/IMG_5301.JPG',
    '/glass.jpg', 
    '/picture1.jpg',
    '/picture2.jpg',
    '/picture3.jpg',
    '/IMG_5300.JPG',
    '/IMG_5301.JPG',
    '/glass.jpg', 
    '/picture1.jpg',
    '/picture2.jpg',
    '/picture3.jpg',
    '/IMG_5300.JPG',
    '/IMG_5301.JPG',
    '/glass.jpg', 
    '/picture1.jpg',
    '/picture2.jpg',
    '/picture3.jpg',
    '/IMG_5300.JPG',
    '/IMG_5301.JPG',
];

export {Image_list};